/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.visionplus.channel.channel_register;

import com.sv.visionplus.base.AbstractObjectCreator;
import com.sv.visionplus.channel.channel_register.model.ChannelModelMix;
import com.sv.visionplus.system.exception.VPException;

/**
 *
 * @author Supervision
 */
public class PCChannel extends AbstractObjectCreator<ChannelModelMix> {

    private ChannelModelMix item;

    /**
     * Creates new form PCChannel
     */
    public PCChannel() {
        initComponents();
        getDoctors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIndexNo = new com.sv.visionplus.util.component.textfield.CIntegerField();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new com.sv.visionplus.util.component.textfield.CDateField();
        jLabel3 = new javax.swing.JLabel();
        cmboDoctor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtChannelDate = new com.sv.visionplus.util.component.textfield.CDateField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtChannelId = new com.sv.visionplus.util.component.textfield.CStringField();
        jLabel14 = new javax.swing.JLabel();
        txtTime = new com.sv.visionplus.util.component.textfield.CStringField();
        jLabel7 = new javax.swing.JLabel();
        txtAmount = new com.sv.visionplus.util.component.textfield.CDoubleField();
        jLabel15 = new javax.swing.JLabel();
        txtPatientName = new com.sv.visionplus.util.component.textfield.CStringField();
        jLabel16 = new javax.swing.JLabel();
        txtMobileNo = new com.sv.visionplus.util.component.textfield.CStringField();
        jLabel8 = new javax.swing.JLabel();
        txtPayAmount = new com.sv.visionplus.util.component.textfield.CDoubleField();

        jLabel1.setText("Invoice No.:");

        jLabel2.setText("Date :");

        jLabel3.setText("Doctor Name :");

        jLabel4.setText("Channel Date :");

        jButton1.setText("Create New Channel No");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Channel Id :");

        jLabel14.setText("Time :");

        jLabel7.setText("Total Amount :");

        txtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setText("Patient Name :");

        jLabel16.setText("Patient Contact No :");

        jLabel8.setText("Pay Amount :");

        txtPayAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChannelId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(txtChannelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmboDoctor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIndexNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPayAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChannelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChannelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int channelId = getChannelId();
        txtChannelId.setCValue(String.valueOf(channelId + 1));

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.sv.visionplus.util.component.textfield.CDoubleField txtAmount;
    private com.sv.visionplus.util.component.textfield.CDateField txtChannelDate;
    private com.sv.visionplus.util.component.textfield.CStringField txtChannelId;
    private com.sv.visionplus.util.component.textfield.CDateField txtDate;
    private com.sv.visionplus.util.component.textfield.CIntegerField txtIndexNo;
    private com.sv.visionplus.util.component.textfield.CStringField txtMobileNo;
    private com.sv.visionplus.util.component.textfield.CStringField txtPatientName;
    private com.sv.visionplus.util.component.textfield.CDoubleField txtPayAmount;
    private com.sv.visionplus.util.component.textfield.CStringField txtTime;
    // End of variables declaration//GEN-END:variables
    private void getDoctors() {
        try {
            java.sql.Connection connection = com.sv.visionplus.util.database.DatabaseUtil.getInstance().openConnection();
            com.sv.visionplus.channel.doctor.DoctorFormDao dao = new com.sv.visionplus.channel.doctor.DoctorFormDao();
            java.util.List<com.sv.visionplus.channel.doctor.model.DoctorModel> searchResult = dao.AllDoctor(connection);
            for (com.sv.visionplus.channel.doctor.model.DoctorModel channel : searchResult) {
                cmboDoctor.addItem(channel.getIndexNo() + " " + channel.getdoctor_name());
            }
        } catch (java.sql.SQLException ex) {
            java.util.logging.Logger.getLogger(PCChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private int getChannelId() {
        try {
            java.util.Date date = txtChannelDate.getCValue();
            java.sql.Connection connection = com.sv.visionplus.util.database.DatabaseUtil.getInstance().openConnection();
            java.util.List<com.sv.visionplus.channel.channel_register.model.ChannelModelMix> list = ChannelFormDAO.getInstance().getSearchResult(connection, com.sv.visionplus.util.formatter.FormatterUtil.getInstance().formatDate(date));
            return list.size();
        } catch (java.sql.SQLException ex) {
            java.util.logging.Logger.getLogger(com.sv.visionplus.channel.doctor.PCDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return 0;
    }

    @Override
    public void setIdealMode() {
        txtIndexNo.setCValueEditable(false);
        cmboDoctor.setEditable(false);
        txtDate.setCValueEditable(false);
        txtChannelDate.setCValueEditable(false);
        txtChannelId.setCValueEditable(false);
        txtAmount.setCValueEditable(false);
        txtPayAmount.setCValueEditable(false);
        txtPatientName.setCValueEditable(false);
        txtMobileNo.setCValueEditable(false);
    }

    @Override
    public void setNewMode() {
        item = new ChannelModelMix();

        txtIndexNo.setCValueEditable(false);
        txtIndexNo.resetCValue();
        txtPatientName.setCValueEditable(true);
        txtPatientName.resetCValue();
        txtMobileNo.setCValueEditable(true);
        txtMobileNo.resetCValue();
        cmboDoctor.setEditable(true);
        txtDate.setCValueEditable(false);
        txtDate.resetCValue();
        txtChannelDate.setCValueEditable(true);
        txtChannelDate.resetCValue();
        txtChannelId.setCValueEditable(false);
        txtChannelId.resetCValue();
        txtAmount.setCValueEditable(true);
        txtAmount.resetCValue();
        txtPayAmount.setCValueEditable(true);
        txtPayAmount.resetCValue();
        int channelId = getChannelId();
        txtChannelId.setCValue(com.sv.visionplus.util.formatter.FormatterUtil.getInstance().formatDate(txtChannelDate.getCValue()) + "_" + (channelId + 1));
    }

    @Override
    public void setEditMode() {
        txtIndexNo.setCValueEditable(false);
        cmboDoctor.setEditable(true);
        txtChannelId.setCValueEditable(true);
        txtAmount.setCValueEditable(true);
        txtPayAmount.setCValueEditable(true);
        txtDate.setCValueEditable(true);
        txtPatientName.setCValueEditable(true);
        txtChannelDate.setCValueEditable(true);
        txtMobileNo.setCValueEditable(true);
    }

    @Override
    public void resetFields() {
        txtIndexNo.resetCValue();
        txtChannelId.resetCValue();
        txtAmount.resetCValue();
        txtPayAmount.resetCValue();
        txtDate.resetCValue();
        txtPatientName.resetCValue();
        txtChannelDate.resetCValue();
        txtMobileNo.resetCValue();
    }

    @Override
    public void initObject() throws VPException {
        item = new ChannelModelMix();
        item.setIndexNo(txtIndexNo.getCValue());
        item.setAmount(txtAmount.getCValue());
        item.setPayAmount(txtPayAmount.getCValue());
        item.setChannelDate(txtChannelDate.getCValue());
        item.setChannelId(txtChannelId.getCValue());
        item.setDate(txtDate.getCValue());
        item.setPatientName(txtPatientName.getCValue());
        item.setMobile(txtMobileNo.getCValue());
        item.setTime(txtTime.getCValue());

        String[] split = cmboDoctor.getSelectedItem().toString().split(" ");
        String docId = split[0];
        String docName = split[1];
        
        item.setDoctorId(Integer.parseInt(docId));
        item.setDoctorName(docName);
    }

    @Override
    public void initInterface() throws VPException {
        txtIndexNo.setCValue(this.item.getIndexNo());
        cmboDoctor.addItem(this.item.getDoctorId() + " " + this.item.getDoctorName());
        txtChannelId.setCValue(this.item.getChannelId());
        txtAmount.setCValue(this.item.getAmount());
        txtPayAmount.setCValue(this.item.getPayAmount());
        txtDate.setCValue(this.item.getDate());
        txtChannelDate.setCValue(this.item.getChannelDate());
        txtTime.setCValue(this.item.getTime());
        txtPatientName.setCValue(this.item.getPatientName());
        txtMobileNo.setCValue(this.item.getMobile());
    }

    @Override
    protected void setValueAbstract(ChannelModelMix object) {
        this.item = object;
    }

    @Override
    protected ChannelModelMix getValueAbstract() {
        return item;
    }

}
